import { createStyles, makeStyles, Theme } from '@material-ui/core'

export const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    active: {},
    champion: {},
    championImage: {},
    championStats: {},
    champions: {},
    clashTeam: {},
    clashTier: {},
    goldShareIcon: {},
    horizontalDivider: {},
    kda: {},
    kdaHigh: {},
    kdaLow: {},
    masteryLevelIcon: {},
    masteryPoints: {},
    match: {},
    matchDefeat: {},
    matchGoldShare: {},
    matchLoses: {},
    matchResult: {},
    matchRole: {},
    matchTotal: {},
    matchVictory: {},
    matchWinLoss: {},
    matchWins: {},
    matches: {},
    summoner: {},
    summonerName: {},
    summoners: {},
    rankImage: {},
    rankLabel: {},
    roleIcon: {},
    root: {},
    tab: {},
    tabHistory: {},
    tabMastery: {},
    tabRanked: {},
    tabs: {},
    teamAbbreviatedName: {},
    teamImage: {},
    teamName: {},
    totalMasteryLabel: {},
    totalMasteryPoints: {},
    verticalDivider: {},
    winRate: {},
  })
)
